version: "3"

services:
  rng:
    image: johnharris85/dc-rng:1.0
    deploy:
      mode: global
    networks:
    - dc-net

  hasher:
    image: johnharris85/dc-hasher:1.0
    deploy:
      replicas: 7
      update_config:
        delay: 5s
        failure_action: rollback
        max_failure_ratio: .5
        monitor: 5s
        parallelism: 1
    networks:
    - dc-net

  webui:
    image: johnharris85/dc-webui:1.0
    ports:
    - "8000:80"
    networks:
    - dc-net

  redis:
    image: redis
    networks:
    - dc-net

  worker:
    image: johnharris85/dc-worker:1.0
    deploy:
      replicas: 10
    networks:
    - dc-net

networks:
  dc-net:
